# Generated by Django 5.2.7 on 2025-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juguetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre completo del juguete', max_length=100)),
                ('categoria', models.CharField(help_text='categoria del juguete', max_length=100)),
                ('garantia', models.TextField(blank=True, help_text='garantia', null=True)),
                ('reseña', models.TextField(blank=True, help_text='pequeña reseña', null=True)),
                ('precio', models.CharField(help_text='precio', max_length=100)),
            ],
        ),
    ]
